version: "3.7"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuperSA2020"
      ACCEPT_EULA: "Y"
  api:
    image: "dockerproject_api"
    build: .
    depends_on:
      - "mssql"
    ports:
      - "8022:80"

