version: "3.7"
services:
  api:
    build: .
    ports:
      - "8022:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuperSA2020"
      ACCEPT_EULA: "Y"
    command :
      cmd dotnet ef update